### PR TITLE
Show overlay message if browser is not latest Google Chrome

### LINKED ISSUE #278: Show sorry message for unsupported browsers
status of browser supports: #254

### PR DESCRIPTION
**Pull request by urelx**
This fixes #278 

Evidence
---
screenshot 2016-05-13 19 35 12
screenshot 2016-05-13 19 34 53

### CODE REVIEW

**Comment by urelx** [comment]
@raynux Please check it out.

@tjorta FYI

**Comment by nickjanssen** [comment]
Why was this merged/needed? It should work fine now on all browsers.

**Comment by urelx** [comment]
Hmm... Something is wrong? @raynux

**Comment by raynux** [comment]
@nickjanssen Does it? I barely recall that a blank screen was shown on Firefox and Safari. Can you double check?

**Comment by nickjanssen** [comment]
Works fine on FF, IE11 and Safari!
screen shot 2016-05-30 at 12 07 43 pm
screen shot 2016-05-30 at 12 08 06 pm
screen shot 2016-05-30 at 12 08 34 pm

**Comment by raynux** [comment]
Awesome!! Does the update support iPad as well?

On Mon, May 30, 2016 at 12:09 PM Nick Janssen <notifications@github.com>
wrote:

> Works fine on FF, IE11 and Safari!
> [image: screen shot 2016-05-30 at 12 07 43 pm]
> <https://cloud.githubusercontent.com/assets/2780160/15638826/481cb7bc-265f-11e6-9b19-6ba11ec6ac50.png>
> [image: screen shot 2016-05-30 at 12 08 06 pm]
> <https://cloud.githubusercontent.com/assets/2780160/15638827/483f6cee-265f-11e6-840a-7481aa6ae0e8.png>
> [image: screen shot 2016-05-30 at 12 08 34 pm]
> <https://cloud.githubusercontent.com/assets/2780160/15638828/485460b8-265f-11e6-88b4-8005f0b10f54.png>
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/reactiveai/cloud-vision-explorer/pull/301#issuecomment-222403457>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMcFYARhZ6arwN7BHnZmz6moqdOke1Tks5qGlTmgaJpZM4Id6P5>
> .
>
-- 
Ray Sakai
Senior Engineer
Reactive Inc.

rsakai@reactive.co.jp
c: +81 80.5486.9566
p: +81 3.4588.9352

**Comment by nickjanssen** [comment]
Mobile support coming soon! That will be a separate commit though

**Pull request merged**
